# -*- coding: utf-8 -*-
"""Sentiment Analysis Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yuY-28yHacSIs-u8a38y_NcflyXCbOKm
"""

import nltk
nltk.download('vader_lexicon')
import pandas as pd
import re
df = pd.read_csv('twitter_training.csv')
df.pop('id')
df.pop('company')
df.fillna("", inplace=True)
c = df[df.feel != "Irrelevant"]
df = c
def preprocess(obj):
  obj = str(obj)
  obj = re.sub(r'^RT[\s]+', '',obj)
  obj = re.sub(r'https?:\/\/.*[\r\n]*', '', obj)
  obj = re.sub(r'#', '', obj)
  obj = re.sub(r'[0-9]', '', obj)
  return obj
df['text'] = df['text'].apply(preprocess)

from nltk.sentiment import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()

for i in range (len(df['text'])):
  # print(i)
  try:
    df['text'][i] = sia.polarity_scores(df['text'][i])
  # df['text'][i] = df['text'][i].pop('compound')
    df['text'][i].popitem()
    a = max(df['text'][i], key=df['text'][i].get)
    if a=="neg":
      a = "Negative"
    elif a=="pos":
      a = "Positive"
    else :
      a = "Neutral"
    df['text'][i]=a
  except KeyError:
    continue